# Generated by Django 2.2.19 on 2021-11-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='booking',
            name='created_by',
            field=models.PositiveSmallIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('cancelled', 'Cancelled'), ('completed', 'completed')], db_index=True, default='booked', max_length=20),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='type',
            field=models.CharField(choices=[('sedan', 'SEDAN'), ('micro', 'MICRO'), ('suv', 'SUV'), ('coupe', 'COUPE'), ('minivan', 'MINI VAN'), ('van', 'VAN')], db_index=True, default='micro', max_length=20),
        ),
    ]
